#pragma once


#define TITLEFONT_SIZE_X 256 + 256
#define TITLEFONT_SIZE_Y 256 + 256
#define TITLEBUTTON_SIZE_X 512
#define TITLEBUTTON_SIZE_Y 512

#define TITLEBG_HALF_SIZE_X 225
#define TITLEBG_HALF_SIZE_Y 400
#define TITLEBUTTON_HALF_SIZE_X 96  
#define TITLEBUTTON_HALF_SIZE_Y 48

#define BUTTON_COLLISION_RIGHT (SCREEN_HALFWIDTH + TITLEBUTTON_SIZE_X) -305
#define BUTTON_COLLISION_LEFT  (SCREEN_HALFWIDTH - TITLEBUTTON_SIZE_X) +305 
#define BUTTON_COLLISION_UP		SCREEN_HALFHEIGHT + 140
#define BUTTON_COLLISION_DOWN	SCREEN_HALFHEIGHT + 255

void InitTitle(void);
void UninitTitle(void);
void UpdateTitle(HWND hWnd);
void DrawTitle(void);

void TitleSetMouse(int index);